- name: Configure Docker and Deploy BankingApp
  hosts: all
  become: true
  tasks:

  - name: Update apt package index
    apt:
      update_cache: yes

  - name: Install required packages
    apt:
      name:
        - docker.io
        - unzip
      state: present

  - name: Start and enable Docker service
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Add current user to Docker group (optional)
    user:
      name: ansibleadmin
      groups: docker
      append: yes

  - name: Pull the latest Docker image
    docker_image:
      name: revati21/bankapp-eta-app
      source: pull

  - name: Remove any existing container
    docker_container:
      name: bankapp-eta-app
      state: absent

  - name: Deploy the Docker container
    docker_container:
      name: bankapp-eta-app
      image: revati21/bankapp-eta-app
      state: started
      restart_policy: always
      ports:
        - "8084:8082"  # Host port 8084 -> Container port 8082
